# ================================================
# appearance
# ================================================

# 256色
set -g default-terminal "tmux-256color"
# set -ag terminal-overrides ",alacritty:RGB"
set -ag terminal-overrides ",xterm-256color:RGB"
set -ag terminal-overrides ",xterm-ghostty:RGB"

# enable visual notification
set-window-option -g monitor-activity on
set -g visual-activity on

# refresh rate (default 15sec)
set -g status-interval 5

# Optional local styling
source-file -q ~/.config/tmux/style.tmux

# ================================================
# keybind
# ================================================

# prefixキーをC-aに変更する
set -g prefix C-a

# C-bのキーバインドを解除する
unbind C-b

# Send prefix to nested tmux sessions.
bind C-a send-prefix

# キーストロークのディレイを減らす
set -sg escape-time 1

# Enable mouse support for pane selection and sidebar interactions.
set -g mouse on

# 設定ファイルをリロードする
bind r source-file $XDG_CONFIG_HOME/tmux/tmux.conf \; display "Reloaded!"

# copy mode with vi keybind
set-window-option -g mode-keys vi

# window navigation
bind h previous-window
bind l next-window

# ================================================
# plugins
# ================================================

source-file -q ~/.config/tmux/plugins.tmux
